# Input file with seq reads, ex.
#                                        cond_A    cond_A_rep1    A_rep1_left.fq    A_rep1_right.fq
#                                        cond_A    cond_A_rep2    A_rep2_left.fq    A_rep2_right.fq
#                                        cond_B    cond_B_rep1    B_rep1_left.fq    B_rep1_right.fq
#                                        cond_B    cond_B_rep2    B_rep2_left.fq    B_rep2_right.fq
# Note: must avoid spaces in filenames in samples.txt
samples_file: "samples.txt"

# trimmomatic is used for both trinity and rnaSPAdes
trimmomatic_parameters: "ILLUMINACLIP:adapters.fasta:2:30:10 SLIDINGWINDOW:4:5 LEADING:5 TRAILING:5 MINLEN:25"

# set to trinity or rnaspades
assembler: "trinity"

# may consider canging TRINITY_PARAMS += "  --min_kmer_cov 1 --min_glue 2  --no_normalize_reads"
trinity_parameters: "--seqType fq"

# set the organism (plant or non-plant) for targetp: pl or non-pl
targetp: "non-pl"

# Strand-specific RNA-Seq read orientation.
#
# For Trinity assembler use
# if paired: RF or FR, (dUTP method = RF)
# if single: F or R.   
#
# This parameter is used for both Trinity and read alignment steps
#
# For example:
# strand_specific: "--SS_lib_type RF"
#
# For rnaSPAdes assembler use
# if paired: fr (normal) or rf (antisense)
# For example:
# strand_specific: "--ss rf"
strand_specific: ""

# For rnaSPAdes assembler select kmer sizes.
# !!! all values must be odd, less than 128 and listed in ascending order !!!
# For example:
# kmers: "21,33,55"
#
# For Illumina 150 bp reads, it is recommended to use: 21,33,55
# For reads between 150 and 249, it is recommended to use: 21,33,55,77
# For 250bp reads and longer, it is recommended to use: 21,33,55,77,99,127
# You can also use single kmer size but it is not recommended by rnaSPAdes. (kmers: "47")
kmers: "21,33,55"

# Can be used for species name etc
annotated_fasta_prefix: ""

# For pfam, rfam, and blast searches
e_value_threshold: "1e-6"

# Dispersion value for edgeR differential expression analysis 
# https://github.com/trinityrnaseq/trinityrnaseq/wiki/Trinity-Differential-Expression#identifying-de-features-no-biological-replicates-proceed-with-caution
# See more about information about dispersion in edgeR manual http://www.bioconductor.org/packages/release/bioc/manuals/edgeR/man/edgeR.pdf
dispersion: "0.1"

# BUSCO lineage
# The assesed lineage is automatically chosen by BUSCO.
# If you want to use specified lineage you can change this parameter
# by specifying the lineage.
# For example:
# lineage: "eudicots_odb10"
# You can list all possible lineages by running "busco --list-datasets"
lineage: "eudicots_odb10"